environment:
  matrix:
      - PATH: C:\\Miniconda3-x64\\Scripts;%PATH%

install:
  - C:\\Miniconda3-x64\\Scripts\\activate
  - conda.exe update -n base -c defaults -y conda
  - conda.exe create -n testenv -y python=3.8
  - conda.exe install -n testenv -y numpy

build: off

test_script:
  - activate testenv
  - python.exe --version
  - C:\\Miniconda3-x64\\envs\\testenv\\python.exe -c "import numpy; print(numpy.__version__)"
